---
- name: Visual Studio Code | Check if _package is installed
  command: dpkg-query -W visual-studio-code
  register: vscode_check_deb
  become: yes
  failed_when: vscode_check_deb.rc > 1
  changed_when: vscode_check_deb.rc == 1
  tags:
    -vscode

- name: Visual Studio Code | Download package
  get_url: url="http://go.microsoft.com/fwlink/?LinkID=760868" dest="/tmp/vsvode.deb"
  when: vscode_check_deb.rc == 1
  tags:
    -vscode

- name: Visual Studio Code | Install package
  apt: deb="/tmp/vsvode.deb"
  become: true
  when: vscode_check_deb.rc == 1
  tags:
    -vscode

- name: Visual Studio Code | Install Extensions
  shell: code --install-extension {{item}} {{extra_extension_params | default("")}}
  with_items: "{{vs_code_packages | default([])}}"
  when: docker_test is not defined
  tags:
    -vscode
    
