---
# tasks file for sa-visual-studio-code

# Install package
- include: install_microsoft_visual_studio_code_apt.yml
  when: ansible_pkg_mgr == 'apt'
- include: install_microsoft_visual_studio_code_dnf.yml
  when: ansible_pkg_mgr == 'dnf'

# Platform independent tasks
- include: install_extensions.yml
